import crypto from 'crypto';
import { getMongoDb, withMongoTransaction } from './mongo-store.js';

const PAGE_SIZE_MAX=100;
const UNITS={WL:1,DL:100,BGL:10000};
function auditId(){return 'audit_'+Date.now()+'_'+crypto.randomBytes(6).toString('hex');}
async function audit(db,{actor,action,targetUserId=null,metadata={}}){await db.collection('auditLogs').insertOne({id:auditId(),actorUserId:actor.id,actorUsername:actor.username,action,targetUserId,metadata,createdAt:new Date()});}
async function admin(req,res,sessionUser){const u=await sessionUser(req).catch(()=>null);if(!u){res.status(401).json({ok:false,error:'not_authenticated'});return null;}if(!u.isAdmin){res.status(403).json({ok:false,error:'admin_required'});return null;}return u;}
function paging(req){const page=Math.max(1,parseInt(req.query.page||'1',10)||1);const limit=Math.min(PAGE_SIZE_MAX,Math.max(1,parseInt(req.query.limit||'25',10)||25));return {page,limit,skip:(page-1)*limit};}
function pub(u,w,p){return {id:u.id,username:u.username,growId:u.growId||null,gtpsLinked:Boolean(u.gtpsLinked&&u.growId),isAdmin:Boolean(u.isAdmin),isBanned:Boolean(u.isBanned),isMuted:Boolean(u.isMuted),createdAt:u.createdAt||null,wallet:w?.balancesWl?{WL:Number(w.balancesWl.WL||0),DL:Number(w.balancesWl.DL||0),BGL:Number(w.balancesWl.BGL||0)}:null,profile:p?{displayName:p.displayName||u.username,avatarId:p.avatarId||'default',adminTag:p.adminTag||'',public:p.public!==false}:null};}
export function installAdminRoutes(app,{sessionUser}){
app.get('/api/admin/dashboard',async(req,res)=>{const a=await admin(req,res,sessionUser);if(!a)return;const db=await getMongoDb();const [users,wallets,ledger,pw,pd,rounds,crash,battles,sessions,chat]=await Promise.all([db.collection('users').countDocuments({}),db.collection('wallets').countDocuments({}),db.collection('ledger').countDocuments({}),db.collection('withdrawals').countDocuments({status:{$in:['PENDING','PROCESSING','UNKNOWN']}}),db.collection('deposits').countDocuments({status:{$in:['PENDING','UNKNOWN']}}),db.collection('gameRounds').countDocuments({status:'ACTIVE'}),db.collection('crashPlayers').countDocuments({status:'active'}),db.collection('caseBattles').countDocuments({status:'open'}),db.collection('sessions').countDocuments({expiresAt:{$gt:new Date()}}),db.collection('chatMessages').countDocuments({createdAt:{$gte:new Date(Date.now()-86400000)}})]);res.json({ok:true,dashboard:{users,wallets,ledgerEntries:ledger,pendingWithdrawals:pw,pendingDeposits:pd,activeGameRounds:rounds,activeCrashPlayers:crash,openCaseBattles:battles,activeSessions:sessions,chatMessages24h:chat},timestamp:new Date().toISOString()});});
app.get('/api/admin/players',async(req,res)=>{const a=await admin(req,res,sessionUser);if(!a)return;const db=await getMongoDb();const {page,limit,skip}=paging(req);const q=String(req.query.q||'').trim();const filter=q?{$or:[{usernameNormalized:{$regex:q,$options:'i'}},{growIdNormalized:{$regex:q,$options:'i'}}]}:{};const [rows,total]=await Promise.all([db.collection('users').find(filter).sort({createdAt:-1}).skip(skip).limit(limit).toArray(),db.collection('users').countDocuments(filter)]);const ids=rows.map(x=>x.id);const [ws,ps]=await Promise.all([db.collection('wallets').find({userId:{$in:ids}}).toArray(),db.collection('profiles').find({userId:{$in:ids}}).toArray()]);const wm=new Map(ws.map(x=>[x.userId,x])),pm=new Map(ps.map(x=>[x.userId,x]));res.json({ok:true,page,limit,total,pages:Math.ceil(total/limit),players:rows.map(u=>pub(u,wm.get(u.id),pm.get(u.id)))});});
app.get('/api/admin/players/:username',async(req,res)=>{const a=await admin(req,res,sessionUser);if(!a)return;const db=await getMongoDb();const u=await db.collection('users').findOne({usernameNormalized:String(req.params.username||'').trim().toLowerCase()});if(!u)return res.status(404).json({ok:false,error:'user_not_found'});const [w,p,s,l,wd,d]=await Promise.all([db.collection('wallets').findOne({userId:u.id}),db.collection('profiles').findOne({userId:u.id}),db.collection('playerStats').findOne({userId:u.id}),db.collection('ledger').find({userId:u.id}).sort({createdAt:-1}).limit(100).toArray(),db.collection('withdrawals').find({userId:u.id}).sort({createdAt:-1}).limit(50).toArray(),db.collection('deposits').find({userId:u.id}).sort({createdAt:-1}).limit(50).toArray()]);res.json({ok:true,player:pub(u,w,p),stats:s,ledger:l,withdrawals:wd,deposits:d});});
app.post('/api/admin/players/:username/moderate',async(req,res)=>{const a=await admin(req,res,sessionUser);if(!a)return;const field=String(req.body?.field||'');const value=Boolean(req.body?.value);if(!['isBanned','isMuted'].includes(field))return res.status(400).json({ok:false,error:'invalid_moderation_field'});const db=await getMongoDb();const u=await db.collection('users').findOne({usernameNormalized:String(req.params.username||'').trim().toLowerCase()});if(!u)return res.status(404).json({ok:false,error:'user_not_found'});await db.collection('users').updateOne({id:u.id},{$set:{[field]:value,updatedAt:new Date()}});await audit(db,{actor:a,action:field+'_'+(value?'enabled':'disabled'),targetUserId:u.id,metadata:{username:u.username}});res.json({ok:true,username:u.username,field,value});});
app.get('/api/admin/audit-log',async(req,res)=>{const a=await admin(req,res,sessionUser);if(!a)return;const db=await getMongoDb();const {page,limit,skip}=paging(req);const filter={};if(req.query.action)filter.action=String(req.query.action).slice(0,80);if(req.query.targetUserId)filter.targetUserId=String(req.query.targetUserId);const [logs,total]=await Promise.all([db.collection('auditLogs').find(filter).sort({createdAt:-1}).skip(skip).limit(limit).toArray(),db.collection('auditLogs').countDocuments(filter)]);res.json({ok:true,page,limit,total,pages:Math.ceil(total/limit),logs:logs.map(({_id,...x})=>x)});});
app.get('/api/admin/transactions',async(req,res)=>{const a=await admin(req,res,sessionUser);if(!a)return;const db=await getMongoDb();const {page,limit,skip}=paging(req);const filter={};if(req.query.username){const u=await db.collection('users').findOne({usernameNormalized:String(req.query.username).trim().toLowerCase()},{projection:{id:1}});filter.userId=u?.id||'__not_found__';}if(req.query.type)filter.type=String(req.query.type).slice(0,60);if(req.query.currency)filter.currency=String(req.query.currency).toUpperCase();const [rows,total]=await Promise.all([db.collection('ledger').find(filter).sort({createdAt:-1}).skip(skip).limit(limit).toArray(),db.collection('ledger').countDocuments(filter)]);res.json({ok:true,page,limit,total,pages:Math.ceil(total/limit),transactions:rows.map(({_id,...x})=>x)});});
app.get('/api/admin/deposits',async(req,res)=>{const a=await admin(req,res,sessionUser);if(!a)return;const db=await getMongoDb();const {page,limit,skip}=paging(req);const filter={};if(req.query.status)filter.status=String(req.query.status).toUpperCase();const [rows,total]=await Promise.all([db.collection('deposits').find(filter).sort({createdAt:-1}).skip(skip).limit(limit).toArray(),db.collection('deposits').countDocuments(filter)]);res.json({ok:true,page,limit,total,pages:Math.ceil(total/limit),deposits:rows.map(({_id,...x})=>x)});});
app.get('/api/admin/withdrawals',async(req,res)=>{const a=await admin(req,res,sessionUser);if(!a)return;const db=await getMongoDb();const {page,limit,skip}=paging(req);const filter={};if(req.query.status)filter.status=String(req.query.status).toUpperCase();const [rows,total]=await Promise.all([db.collection('withdrawals').find(filter).sort({createdAt:-1}).skip(skip).limit(limit).toArray(),db.collection('withdrawals').countDocuments(filter)]);res.json({ok:true,page,limit,total,pages:Math.ceil(total/limit),withdrawals:rows.map(({_id,...x})=>x)});});
app.post('/api/admin/players/:username/balance',async(req,res)=>{const a=await admin(req,res,sessionUser);if(!a)return;const currency=String(req.body?.currency||'DL').toUpperCase();const amount=Number(req.body?.amount);const mode=String(req.body?.mode||'');if(!UNITS[currency]||!Number.isFinite(amount)||amount<=0||!['add','remove'].includes(mode))return res.status(400).json({ok:false,error:'invalid_balance_adjustment'});const db=await getMongoDb();const u=await db.collection('users').findOne({usernameNormalized:String(req.params.username||'').trim().toLowerCase()});if(!u)return res.status(404).json({ok:false,error:'user_not_found'});const delta=Math.round(amount*UNITS[currency]);try{const result=await withMongoTransaction(async(session,mongo)=>{const fresh=await mongo.collection('users').findOne({id:u.id},{session});const w=await mongo.collection('wallets').findOne({userId:u.id},{session});const current=Number(w?.balancesWl?.[currency]||0),next=current+(mode==='add'?delta:-delta);if(next<0)return {error:'insufficient_balance'};const balances={WL:Number(w?.balancesWl?.WL||0),DL:Number(w?.balancesWl?.DL||0),BGL:Number(w?.balancesWl?.BGL||0)};balances[currency]=next;const ref='admin_'+Date.now()+'_'+crypto.randomBytes(5).toString('hex');await mongo.collection('wallets').updateOne({userId:u.id},{$set:{balancesWl:balances,balanceDls:balances.DL/100,updatedAt:new Date()}},{upsert:true,session});await mongo.collection('ledger').insertOne({id:'txn_'+crypto.randomUUID(),userId:u.id,username:fresh.username,type:'ADMIN_ADJUSTMENT',currency,amount:(mode==='add'?delta:-delta)/UNITS[currency],amountWl:mode==='add'?delta:-delta,balanceBefore:current/UNITS[currency],balanceAfter:next/UNITS[currency],balanceBeforeWl:current,balanceAfterWl:next,referenceId:ref,metadata:{admin:a.username,mode},createdAt:new Date()},{session});await audit(mongo,{actor:a,action:'balance_adjustment',targetUserId:u.id,metadata:{username:fresh.username,currency,amount,mode,referenceId:ref}});return {balancesWl:balances};});if(result.error)return res.status(400).json({ok:false,error:result.error});res.json({ok:true,username:u.username,currency,amount,mode,balancesWl:result.balancesWl});}catch{res.status(500).json({ok:false,error:'balance_adjustment_failed'});}});
}